name: Deploy Skillmatch to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: kigojomo/skillmatch-frontend:latest

      - name: Build and push Backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: kigojomo/skillmatch-backend:latest

  deploy:
    name: Deploy to EC2 Instance
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_SSH_PRIVATE_KEY }}
          script: |
            docker network create skillmatch-network || true

            docker pull kigojomo/skillmatch-frontend:latest
            docker pull kigojomo/skillmatch-backend:latest

            docker stop skillmatch-frontend || true
            docker rm skillmatch-frontend || true
            docker stop skillmatch-backend || true
            docker rm skillmatch-backend || true

            echo "Creating backend .env file..."
            cat << 'EOF' > backend.env
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            TOKEN_EXPIRY=${{ secrets.TOKEN_EXPIRY }}
            CORS_ORIGIN=${{ secrets.CORS_ORIGIN }}
            PORT=${{ secrets.PORT }}
            NODE_ENV=production
            EOF

            chmod 600 backend.env
            echo "Backend .env file created."

            docker run -d --name skillmatch-frontend -p 80:80 --network skillmatch-network kigojomo/skillmatch-frontend:latest

            docker run -d --name skillmatch-backend -p 3000:3000 --network skillmatch-network --env-file ./backend.env kigojomo/skillmatch-backend:latest

            docker image prune -af
